const User = require('../user/user.model');
const { generateTokens, verifyRefreshToken } = require('../../utils/generateToken');
const ApiError = require('../../utils/apiError');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');

class AuthService {
  async register(userData) {
    const { firstName, lastName, email, password } = userData;
    
    // Validate required fields
    if (!firstName || !lastName) {
      throw new ApiError(400, 'First name and last name are required');
    }
    
    if (!email) {
      throw new ApiError(400, 'Email is required');
    }
    
    if (!password || password.length < 6) {
      throw new ApiError(400, 'Password must be at least 6 characters');
    }
    
    const userExists = await User.findOne({ email });
    if (userExists) {
      throw new ApiError(400, 'User already exists');
    }
    
    // Create user - name is auto-generated by the pre-save hook
    const user = await User.create({
      firstName,
      lastName,
      email,
      password,
      authProvider: 'local'
    });
    
    const { accessToken, refreshToken } = generateTokens(user._id);
    
    // Save refresh token
    user.refreshToken = refreshToken;
    user.refreshTokenExpire = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
    user.lastLogin = new Date();
    await user.save({ validateBeforeSave: false });
    
    return {
      user: {
        _id: user._id,
        name: user.name,
        firstName: user.firstName,
        lastName: user.lastName,
        email: user.email,
        role: user.role,
        authProvider: user.authProvider,
        onboardingCompleted: user.onboardingCompleted,
        onboardingStep: user.onboardingStep
      },
      accessToken,
      refreshToken
    };
  }
  
  async login(email, password) {
    if (!email || !password) {
      throw new ApiError(400, 'Email and password are required');
    }
    
    const user = await User.findOne({ email, authProvider: 'local' }).select('+password');
    
    if (!user) {
      throw new ApiError(401, 'Invalid credentials');
    }
    
    // Check if account is locked
    if (user.isLocked()) {
      throw new ApiError(423, 'Account is temporarily locked. Please try again later');
    }
    
    const isPasswordMatch = await user.matchPassword(password);
    
    if (!isPasswordMatch) {
      await user.incLoginAttempts();
      throw new ApiError(401, 'Invalid credentials');
    }
    
    // Reset login attempts on successful login
    if (user.loginAttempts > 0) {
      user.loginAttempts = 0;
      user.lockUntil = undefined;
    }
    
    const { accessToken, refreshToken } = generateTokens(user._id);
    
    // Save refresh token
    user.refreshToken = refreshToken;
    user.refreshTokenExpire = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
    user.lastLogin = new Date();
    await user.save({ validateBeforeSave: false });
    
    return {
      user: {
        _id: user._id,
        name: user.name,
        firstName: user.firstName,
        lastName: user.lastName,
        email: user.email,
        role: user.role,
        authProvider: user.authProvider,
        onboardingCompleted: user.onboardingCompleted,
        onboardingStep: user.onboardingStep,
        avatar: user.avatar
      },
      accessToken,
      refreshToken
    };
  }
  
  // Handle OAuth login/register
  async oauthLogin(profile, provider) {
    const { accessToken, refreshToken } = generateTokens(profile._id);
    
    // Save refresh token
    profile.refreshToken = refreshToken;
    profile.refreshTokenExpire = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
    await profile.save({ validateBeforeSave: false });
    
    return {
      user: {
        _id: profile._id,
        name: profile.name,
        firstName: profile.firstName,
        lastName: profile.lastName,
        email: profile.email,
        role: profile.role,
        authProvider: profile.authProvider,
        onboardingCompleted: profile.onboardingCompleted,
        onboardingStep: profile.onboardingStep,
        avatar: profile.avatar
      },
      accessToken,
      refreshToken
    };
  }
  
  async refreshAccessToken(refreshToken) {
    if (!refreshToken) {
      throw new ApiError(401, 'Refresh token required');
    }
    
    try {
      const decoded = verifyRefreshToken(refreshToken);
      
      const user = await User.findById(decoded.id).select('+refreshToken +refreshTokenExpire');
      
      if (!user || user.refreshToken !== refreshToken) {
        throw new ApiError(401, 'Invalid refresh token');
      }
      
      if (user.refreshTokenExpire < new Date()) {
        throw new ApiError(401, 'Refresh token expired');
      }
      
      const { accessToken, refreshToken: newRefreshToken } = generateTokens(user._id);
      
      // Rotate refresh token
      user.refreshToken = newRefreshToken;
      user.refreshTokenExpire = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
      await user.save({ validateBeforeSave: false });
      
      return {
        accessToken,
        refreshToken: newRefreshToken
      };
    } catch (error) {
      throw new ApiError(401, 'Invalid refresh token');
    }
  }
  
  async logout(userId) {
    const user = await User.findById(userId).select('+refreshToken');
    user.refreshToken = undefined;
    user.refreshTokenExpire = undefined;
    await user.save({ validateBeforeSave: false });
    
    return { message: 'Logged out successfully' };
  }
  
  async forgotPassword(email) {
    const user = await User.findOne({ email, authProvider: 'local' });
    
    if (!user) {
      throw new ApiError(404, 'User not found or account uses social login');
    }
    
    // Generate reset token
    const resetToken = crypto.randomBytes(32).toString('hex');
    
    user.passwordResetToken = crypto
      .createHash('sha256')
      .update(resetToken)
      .digest('hex');
    
    user.passwordResetExpire = new Date(Date.now() + 10 * 60 * 1000);
    
    await user.save({ validateBeforeSave: false });
    
    return { message: 'Password reset token generated' };
  }

  async resetPassword(resetToken, newPassword) {
    const hashedToken = crypto
      .createHash('sha256')
      .update(resetToken)
      .digest('hex');
    
    const user = await User.findOne({
      passwordResetToken: hashedToken,
      passwordResetExpire: { $gt: new Date() },
      authProvider: 'local'
    }).select('+password');
    
    if (!user) {
      throw new ApiError(400, 'Invalid or expired reset token');
    }
    
    user.password = newPassword;
    user.passwordResetToken = undefined;
    user.passwordResetExpire = undefined;
    user.passwordChangedAt = new Date();
    
    await user.save();
    
    return { message: 'Password reset successful' };
  }
  
  async changePassword(userId, currentPassword, newPassword) {
    const user = await User.findById(userId).select('+password');
    
    if (!user) {
      throw new ApiError(404, 'User not found');
    }
    
    if (user.authProvider !== 'local') {
      throw new ApiError(400, 'Cannot change password for social login accounts');
    }
    
    const isPasswordMatch = await user.matchPassword(currentPassword);
    
    if (!isPasswordMatch) {
      throw new ApiError(401, 'Current password is incorrect');
    }
    
    user.password = newPassword;
    user.passwordChangedAt = new Date();
    await user.save();
    
    return { message: 'Password changed successfully' };
  }
  
  // Onboarding methods
  async saveOnboardingStep(userId, stepData) {
    const user = await User.findById(userId);
    
    if (!user) {
      throw new ApiError(404, 'User not found');
    }
    
    const { step, data } = stepData;
    
    switch (step) {
      case 1:
        if (data.location) user.location = data.location;
        if (data.professionalExperience) user.professionalExperience = data.professionalExperience;
        if (data.currentRole) user.currentRole = data.currentRole;
        if (data.industry) user.industry = data.industry;
        if (data.roleLocation) user.roleLocation = data.roleLocation;
        if (data.skills) user.skills = data.skills;
        break;
        
      case 2:
        if (data.primaryCareerGoal) user.primaryCareerGoal = data.primaryCareerGoal;
        if (data.targetRoles) user.targetRoles = data.targetRoles;
        if (data.goalReviewTimeline) user.goalReviewTimeline = data.goalReviewTimeline;
        break;
        
      default:
        throw new ApiError(400, 'Invalid onboarding step');
    }
    
    user.onboardingStep = step;
    
    if (step === 2) {
      user.onboardingCompleted = true;
    }
    
    await user.save({ validateBeforeSave: false });
    
    return {
      onboardingCompleted: user.onboardingCompleted,
      onboardingStep: user.onboardingStep,
      message: user.onboardingCompleted ? 'Onboarding completed' : 'Step saved'
    };
  }
  
  async skipOnboardingStep(userId, step) {
    const user = await User.findById(userId);
    
    if (!user) {
      throw new ApiError(404, 'User not found');
    }
    
    user.onboardingStep = step;
    
    if (step === 2) {
      user.onboardingCompleted = true;
    }
    
    await user.save({ validateBeforeSave: false });
    
    return {
      onboardingCompleted: user.onboardingCompleted,
      onboardingStep: user.onboardingStep,
      message: user.onboardingCompleted ? 'Onboarding completed' : `Step ${step} skipped`
    };
  }
  
  async getOnboardingStatus(userId) {
    const user = await User.findById(userId)
      .select('onboardingCompleted onboardingStep firstName lastName email');
    
    if (!user) {
      throw new ApiError(404, 'User not found');
    }
    
    return {
      onboardingCompleted: user.onboardingCompleted,
      onboardingStep: user.onboardingStep,
      user: {
        firstName: user.firstName,
        lastName: user.lastName,
        email: user.email
      }
    };
  }
  
  async getMe(userId) {
    const user = await User.findById(userId)
      .select('-__v')
      .populate('savedResources', 'title category')
      .populate('followers', 'name email')
      .populate('following', 'name email');
    
    if (!user) {
      throw new ApiError(404, 'User not found');
    }
    
    return user;
  }
}

module.exports = new AuthService();